DROP TABLE IF EXISTS dimension_table;

CREATE TABLE dimension_table AS
SELECT 
	DISTINCT ON (STOCK_CODE) STOCK_CODE,
	STOCK_NAME,
	COMPANY_NAME,
	MARKET_NAME,
	SECTOR,
	CAST(SYARIAH AS BOOL)
from raw_table;