DROP TABLE IF EXISTS fact_table;

CREATE TABLE fact_table AS
SELECT 
	STOCK_CODE,
	CASE
		WHEN MARKET_CAP~E'^^[0-9\.]+m$' THEN
			CAST(CAST (SUBSTRING(MARKET_CAP, 1, LENGTH(MARKET_CAP)-1) AS DOUBLE PRECISION) * 1000000 AS BIGINT)
		WHEN MARKET_CAP~E'^^[0-9\.]+b$' THEN
			CAST(CAST (SUBSTRING(MARKET_CAP, 1, LENGTH(MARKET_CAP)-1) AS DOUBLE PRECISION) * 1000000000 AS BIGINT)
		ELSE
			NULL
	END as MARKET_CAP,
	CAST(LAST_PRICE AS DOUBLE PRECISION),
	CASE
		WHEN PE_RATIO~E'^^[0-9\.]+$' THEN
			CAST (PE_RATIO AS DOUBLE PRECISION)
		ELSE
			NULL
	END as PE_RATIO,
	CASE
		WHEN DY~E'^^[0-9\.]+$' THEN
			CAST (DY AS DOUBLE PRECISION)
		ELSE
			NULL
	END as DY,
	CASE
		WHEN ROE~E'^^[0-9\.]+$' THEN
			CAST (ROE AS DOUBLE PRECISION)
		ELSE
			NULL
	END as ROE,
    UPDATED_TS
from 
	raw_table;