-- create raw table
DROP TABLE IF EXISTS raw;

CREATE TABLE IF NOT EXISTS raw (
    COMPANY_NAME VARCHAR,
    STOCK_NAME VARCHAR,
    STOCK_CODE VARCHAR,
    MARKET_NAME VARCHAR,
    SYARIAH VARCHAR,
    SECTOR VARCHAR,
    MARKET_CAP VARCHAR,
    LAST_PRICE VARCHAR,
    PE_RATIO VARCHAR,
    DY VARCHAR,
    ROE VARCHAR
);